language: perl

addons:
  postgresql: "9.4"

before_install:
  - sudo apt-get update
  - sudo apt-get install postgresql-plperl-9.4

script:
  - perl Build.PL
  - ./Build
  - ./Build test --verbose 1
  - ./Build install

perl:
  - "5.16"
  - "5.12"

env:
  - TEST_PLPERL=1 TEST_POSTGIS_BASE=/usr/share/postgresql/9.4/contrib/postgis-2.1 MBD_SCRATCH_PGHOST=localhost MBD_SCRATCH_PGPORT=5432
  - TEST_PLPERL=1 TEST_POSTGIS_BASE=/usr/share/postgresql/9.4/contrib/postgis-2.1
