---
abstract: 'Manage database patches in the style of Module::Build.'
author:
  - 'Brian Duggan <brian.duggan@nasa.gov>'
build_requires:
  File::Copy::Recursive: 0
  File::Slurp: 0
  IO::Socket::INET: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Build-Database
provides:
  Module::Build::Database:
    file: lib/Module/Build/Database.pm
    version: 0.12
  Module::Build::Database::PostgreSQL:
    file: lib/Module/Build/Database/PostgreSQL.pm
  Module::Build::Database::PostgreSQL::Templates:
    file: lib/Module/Build/Database/PostgreSQL/Templates.pm
resources:
  license: http://dev.perl.org/licenses/
version: 0.12
