---
name: Module-Build-Database
version: 0.05
author:
  - 'Brian Duggan <brian.duggan@nasa.gov>'
abstract: Manage database patches in the style of Module::Build.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  File::Copy::Recursive: 0
  File::Slurp: 0
  IO::Socket::INET: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.340201
provides:
  Module::Build::Database:
    file: lib/Module/Build/Database.pm
    version: 0.05
  Module::Build::Database::PostgreSQL:
    file: lib/Module/Build/Database/PostgreSQL.pm
  Module::Build::Database::PostgreSQL::Templates:
    file: lib/Module/Build/Database/PostgreSQL/Templates.pm
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
